### ISSUE TITLE
로고 및 테마색 선택

### ISSUE THREAD

**Issue by sohy19** [HamBab/hambab-client#4]

**Comment by sasha1107** [comment]
[함밥 이미지.zip](https://github.com/HamBab/hambab-client/files/9305374/default.zip)

**Comment by sasha1107** [comment]
[함밥 이미지.zip](https://github.com/HamBab/hambab-client/files/9315612/default.zip)

**Comment by sohy19** [comment]
수고하셨습니다 ~!!
